// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	DeleteUserByID(ctx context.Context, id int32) (int64, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	IsUserValid(ctx context.Context, login string) (User, error)
	UpdateUserPwd(ctx context.Context, arg UpdateUserPwdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
